# Generated by Django 3.2.13 on 2022-05-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rimapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apierror',
            name='ip_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
