# Generated by Django 2.0.4 on 2018-08-07 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Group Name', max_length=50)),
                ('note', models.TextField(help_text='Notes')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rim.Group'),
        ),
    ]
