# Generated by Django 2.0.4 on 2018-07-18 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='count',
            field=models.IntegerField(help_text='Count'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_model',
            field=models.CharField(help_text='Equipment Model', max_length=30),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.ForeignKey(help_text='Equipment Type', on_delete=django.db.models.deletion.CASCADE, to='rim.EquipmentType'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_no',
            field=models.CharField(help_text='Serial No.', max_length=100),
        ),
    ]
