# Generated by Django 2.0.4 on 2018-09-05 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rim', '0002_auto_20180718_2222'),
        ('rim', '0002_auto_20180725_2108'),
    ]

    operations = [
    ]
