# Generated by Django 2.0.4 on 2018-09-02 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rim', '0002_auto_20180725_2108'),
        ('rim', '0002_auto_20180807_2246'),
    ]

    operations = [
    ]
