# Generated by Django 2.0.4 on 2018-09-06 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rim', '0003_auto_20180906_1713'),
        ('rim', '0004_auto_20180906_1703'),
    ]

    operations = [
    ]
