# Generated by Django 2.0.4 on 2018-10-02 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rim', '0005_merge_20180906_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='latest_checkout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rim.Checkout'),
        ),
    ]
