# Generated by Django 3.0.4 on 2020-03-09 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rim', '0008_auto_20181206_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='physical_address',
        ),
        migrations.AddField(
            model_name='equipment',
            name='mac_address',
            field=models.CharField(blank=True, max_length=30, verbose_name='MAC address'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bpn',
            field=models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator('[mM8]\\d{8}', "Bearpass number must start with an 'M,' 'm,' or '8,' and followed by eight digits.")], verbose_name='Client M-number'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_no',
            field=models.CharField(max_length=100, verbose_name='Serial number'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='smsu_tag',
            field=models.CharField(blank=True, max_length=30, verbose_name='SMSU tag'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='usb_ports',
            field=models.IntegerField(blank=True, null=True, verbose_name='USB ports'),
        ),
    ]
