# Generated by Django 3.0.4 on 2020-03-09 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rim', '0008_auto_20181206_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='physical_address',
            new_name='MAC_address',
        ),
        migrations.AlterField(
            model_name='client',
            name='bpn',
            field=models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator('[mM8]\\d{8}', "Bearpass number must start with an 'M,' 'm,' or '8,' and followed by eight digits.")], verbose_name='Client M-number'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Client Name'),
        ),
    ]
