# Generated by Django 3.0.4 on 2020-03-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rim', '0012_auto_20200311_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='serial_no',
            field=models.CharField(max_length=100, unique=True, verbose_name='Serial number'),
        ),
    ]
