# Generated by Django 3.0.4 on 2020-03-25 18:04

from django.db import migrations

def capitalize_serial_nums(apps, schema_editor):
    Equipment = apps.get_model('rim', 'Equipment')
    for e in Equipment.objects.all():
        e.serial_no = e.serial_no.upper()
        e.save()

class Migration(migrations.Migration):

    dependencies = [
        ('rim', '0013_auto_20200324_1726'),
    ]

    operations = [
        migrations.RunPython(capitalize_serial_nums)
    ]
