# Generated by Django 3.0.4 on 2020-03-25 18:04

from django.db import migrations
from django.db.models.functions import Upper

def capitalize_serial_nums(apps, schema_editor):
    Equipment = apps.get_model('rim', 'Equipment')
    Equipment.objects.update(serial_no=Upper('serial_no'))

def reverse(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('rim', '0013_auto_20200324_1726'),
    ]

    operations = [
        migrations.RunPython(capitalize_serial_nums, reverse)
    ]
