# Generated by Django 3.2.13 on 2022-05-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rim', '0014_auto_20200325_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='displays',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='equipment',
            name='network_cards',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='equipment',
            name='users_info',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='hard_drive',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='video_card',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
