# Generated by Django 3.2.13 on 2022-05-25 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rim', '0014_auto_20200325_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='hard_drive',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='video_card',
        ),
        migrations.AddField(
            model_name='equipment',
            name='GPU',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='equipment',
            name='displays',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='equipment',
            name='network_cards',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='equipment',
            name='storage',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='equipment',
            name='users_info',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rim.equipmenttype'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='memory',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='type_name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Equipment Type'),
        ),
    ]
