# Generated by Django 3.2.13 on 2022-06-02 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rim', '0015_auto_20220525_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='usb_ports',
        ),
    ]
