# Generated by Django 3.2.15 on 2022-09-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rim', '0015_auto_20220525_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkout',
            options={'ordering': ['-timestamp']},
        ),
    ]
