# Generated by Django 3.2.15 on 2023-03-07 17:59

from datetime import datetime
from django.db import migrations, models
from django.utils.timezone import make_aware, utc


def forwards(apps, schema_editor):
    Equipment = apps.get_model('rim', 'Equipment')
    Equipment.objects.all().update(last_modified=datetime(2000, 1, 1, tzinfo=utc))


class Migration(migrations.Migration):

    dependencies = [
        ('rim', '0016_alter_checkout_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
