# Generated by Django 3.2.15 on 2024-03-27 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rim', '0017_equipment_last_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.IntegerField(blank=True, default=0)),
                ('disabled', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_model',
            field=models.CharField(max_length=64),
        ),
        migrations.AddField(
            model_name='equipment',
            name='operating_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rim.operatingsystem'),
        ),
    ]
