# Generated by Django 3.2.25 on 2026-02-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rim', '0018_auto_20240327_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='autopilot_hash',
            field=models.CharField(blank=True, max_length=8192),
        ),
        migrations.AddField(
            model_name='equipment',
            name='netboot_guid',
            field=models.CharField(blank=True, max_length=64, verbose_name='Netboot GUID'),
        ),
    ]
